# spring configuration
spring:
  application:
    name: jblog

  # devtools - live reload
  devtools:
    livereload:
      enabled: true

  # aop
  aop:
    auto: true
    proxy-target-class: true

  # mvc
  mvc:
    static-path-pattern: /assets/**
    throw-exception-if-no-handler-found: true
  #   view:
  #      prefix: /WEB-INF/views/
  #      suffix: .jsp

  # web
  web:
    resources:
      static-locations: file:/Users/jiyoon/jblog-uploads/, classpath:assets/

  # message resources(internationalization = i18n i와 n 사이에 18글자가 있어서)
  messages:
    basename: messages/message
    encoding: utf-8
    always-use-message-format: true

  # multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 10MB

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.7:3306/jblog?charset=utf8
    username: jblog
    password: jblog
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml

# server configuration
server:
  port: 8080
  servlet:
    context-path: /jblog6
    encoding:
      charset: UTF-8
      enabled: true
  error:
    whitelabel:
      enabled: false
    path: /error

# logging
logging:
  config: classpath:logback.xml